csp = {
    "default-src": "'self'",
    "style-src": [
        "'self'",
        "stackpath.bootstrapcdn.com",
        "'unsafe-inline'",
    ],
    "script-src": [
        "'self'",
        "'strict-dynamic'",
        "www.google-analytics.com",
        "www.googletagmanager.com",
        "cdnjs.cloudflare.com",
        "cdn.jsdelivr.net",
        "stackpath.bootstrapcdn.com",
        "pagecdn.io",
        "'unsafe-inline'",
    ],
    "font-src": ["'none'"],
    "connect-src": ["'none'"],
    "img-src": ["'self'", "data:"],
    "frame-src": ["'none'"],
    "object-src": ["'none'"],
    "base-uri": ["'none'"],
}
